config/routes.rb
Rails.application.routes.draw do


  resources :listing_assets, only: [:index,:new, :create, :show]
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
 
  get '/account',  to: 'account#index'
  
  get '/adjust',   to: 'adjust#index'
  get '/adjust/edit',  to: 'adjust#edit'
  get '/adjust/show',  to: 'adjust#show'
  post '/adjust/create', to: 'adjust#create'
  get 'adjust/index'

  get '/user/history', to: 'asset_histories#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/adjust_controller.rb
class AdjustController < ApplicationController
  authorize_resource :class => false

  def index
      @users = User.paginate(page: params[:page])
      render "index"
  end
  
  def edit
    @user = User.find_by_email(params[:email])
    
    if @user == nil
      redirect_to adjust_path
      return
    end  
    
    populate_assets
    render "edit"
  end
  
  def show
    @user = User.find_by_email(params[:email])
    respond_to do |format|
      format.html { render "adjust" }
      format.js
    end
  end  
  
  def create
    
    user = User.find_by_email(history_params[:user_email])

    @ah = user.asset_histories.build(history_params)
    
    unless @ah.valid?
      flash[:alert] = @ah.errors.full_messages
        respond_to do |format|
          format.html { redirect_to adjust_show_path email: history_params[:user_email], asset:  history_params[:asset_type] }
          format.js
        end
      return
    end
    @ah.action_type = :manual_adjust
    @ah.created_by = current_user.email
    
    asset = user.assets.find_by_symbol(@ah.asset_type)
    asset = user.assets.create(symbol: @ah.asset_type, amount: 0) unless asset
    
    
    
    asset.transaction do 
      begin
        asset.amount = asset.amount + @ah.amount
        asset.save!
        @ah.save!
        
        flash[:notice] = "Adjust success!"
        
        respond_to do |format|
          format.html { redirect_to user_history_path user_id: user.id }
          format.js
        end
        
      rescue ActiveRecord::RecordInvalid 
        flash[:alert] = @ah.errors.full_messages
        respond_to do |format|
          format.html { redirect_to adjust_show_path email: history_params[:user_email], asset:  history_params[:asset_type] }
          format.js
        end
        
      rescue Exception
        flash[:alert] = caller
        respond_to do |format|
          format.html { redirect_to adjust_show_path email: history_params[:user_email], asset:  history_params[:asset_type] }
          format.js
        end
      end
    end
    
  end  
  
  private
  
  def history_params 
    params.require(:asset_history).permit(:user_email, :asset_type, :amount)
  end
  
  def populate_assets
    @assets = Hash.new
    current_user.assets.map do |x|  
      @assets[x.symbol] = x.amount
    end
  end
  
end

app/helpers/adjust_helper.rb
module AdjustHelper
end

app/views/adjust/_assets.html.erb
<h1>Account Summary</h1>
<table class="table table-bordered">
    <thead>
      <tr>
        <th>Asset</th>
        <th>Amount</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% ListingAsset.all.each do |a| %>
      <tr>
        <td><%= a.name %></td>
        <td><%= @assets[a.name] || 0  %></td>
        <td><%= link_to "change", adjust_show_path(email: @user.email, asset: a['symbol']) %></td>
      </tr>
      <% end %>
      
    </tbody>
  </table>

app/views/adjust/adjust.html.erb
<h3>Adjust Amount</h3>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :asset_history, url: adjust_create_path do |f| %>
      
      <%= f.label :user_email %><br />
      <%= f.email_field :user_email,  class: 'form-control',value: @user.email, readonly: true %>
      
    
      
      <%= f.label :asset_type %><br />
      <%= f.text_field :asset_type, class: 'form-control', value: params[:asset], readonly: true %>

      <%= f.label :amount %><br />
      <%= f.number_field :amount,autofocus: true, step: :any, class: 'form-control' %>

      <%= f.submit "Submit" ,class: "btn btn-primary"%>
      
    <% end %>
  </div>
</div>

app/views/adjust/edit.html.erb
<%= render "adjust/assets" %>

app/views/adjust/index.html.erb
<h3>Users:</h3>
<%= will_paginate @users %>

    <ul class="users">
      <% @users.each do |user| %>
        <li>
          <%= link_to user.email, adjust_edit_path(email: user.email) %>
        </li>
      <% end %>
    </ul>
<%= will_paginate @users %>