config/routes.rb
Rails.application.routes.draw do


  resources :listing_assets, only: [:index,:new, :create, :show]
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
 
  get '/account',  to: 'account#index'
  
  get '/adjust',   to: 'adjust#index'
  get '/adjust/edit',  to: 'adjust#edit'
  get '/adjust/show',  to: 'adjust#show'
  post '/adjust/create', to: 'adjust#create'
  get 'adjust/index'

  get '/user/history', to: 'asset_histories#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing_asset.rb
class ListingAsset < ApplicationRecord
end

app/controllers/listing_assets_controller.rb
class ListingAssetsController < ApplicationController
  before_action :set_listing_asset, only: [:show]

  # GET /listing_assets
  # GET /listing_assets.json
  def index
    @listing_assets = ListingAsset.all
  end

  # GET /listing_assets/1
  # GET /listing_assets/1.json
  def show
  end

  # GET /listing_assets/new
  def new
    @listing_asset = ListingAsset.new
  end

  # GET /listing_assets/1/edit
  def edit
  end

  # POST /listing_assets
  # POST /listing_assets.json
  def create
    @listing_asset = ListingAsset.new(listing_asset_params)

    respond_to do |format|
      if @listing_asset.save
        format.html { redirect_to @listing_asset, notice: 'Listing asset was successfully created.' }
        format.json { render :show, status: :created, location: @listing_asset }
      else
        format.html { render :new }
        format.json { render json: @listing_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listing_assets/1
  # PATCH/PUT /listing_assets/1.json
  def update
    respond_to do |format|
      if @listing_asset.update(listing_asset_params)
        format.html { redirect_to @listing_asset, notice: 'Listing asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing_asset }
      else
        format.html { render :edit }
        format.json { render json: @listing_asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listing_assets/1
  # DELETE /listing_assets/1.json
  def destroy
    @listing_asset.destroy
    respond_to do |format|
      format.html { redirect_to listing_assets_url, notice: 'Listing asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing_asset
      @listing_asset = ListingAsset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_asset_params
      params.require(:listing_asset).permit(:name)
    end
end

app/helpers/listing_assets_helper.rb
module ListingAssetsHelper
end

app/views/listing_assets/_form.html.erb
<%= form_with(model: listing_asset, local: true) do |form| %>
  <% if listing_asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing_asset.errors.count, "error") %> prohibited this listing_asset from being saved:</h2>

      <ul>
      <% listing_asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :listing_asset_name ,class: 'form-control'%>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listing_assets/edit.html.erb
<h1>Editing Listing Asset</h1>

<%= render 'form', listing_asset: @listing_asset %>

<%= link_to 'Show', @listing_asset %> |
<%= link_to 'Back', listing_assets_path %>

app/views/listing_assets/index.html.erb
<h1>Listing Assets</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @listing_assets.each do |listing_asset| %>
      <tr>
        <td><%= listing_asset.name %></td>
        <td><%= link_to 'Show', listing_asset %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to 'New Listing Asset', new_listing_asset_path, class: "btn btn-primary", method: :get %>

app/views/listing_assets/new.html.erb
<h1>New Listing Asset</h1>


<%= render 'form', listing_asset: @listing_asset %>

<%= button_to 'Back', listing_assets_path, method: :get,class: "btn btn-primary" %>

app/views/listing_assets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing_asset.name %>
</p>

<%= link_to 'Back', listing_assets_path %>