config/routes.rb
Rails.application.routes.draw do


  resources :listing_assets, only: [:index,:new, :create, :show]
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
 
 
  get '/account',  to: 'account#index'
  
  get '/adjust',   to: 'adjust#index'
  get '/adjust/edit',  to: 'adjust#edit'
  get '/adjust/show',  to: 'adjust#show'
  post '/adjust/create', to: 'adjust#create'
  get 'adjust/index'

  get '/user/history', to: 'asset_histories#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.etf.one/">ETF-One</a>
    by <a href="http://kidylee.com/">Li An</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ETF One", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <% if current_user.try(:admin?) %>
         <li class="dropdown">
           <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin<span class="caret"></span></a>
           <ul class="dropdown-menu">
              <li><%= link_to 'Amount Adjustment', adjust_path, :class => 'navbar-link' %></li>
              <li><%= link_to 'Add Listing', listing_assets_path, :class => 'navbar-link' %></li>
           </ul>

         </li>
        <% end %>
        <% if user_signed_in? %>
            <li><%= link_to 'Account', account_path, :class => 'navbar-link' %></li>
            <li><%= link_to 'History', user_history_path, :class => 'navbar-link' %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <% else %>
            <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<% if alert.kind_of?(Array) %>
		<% alert.each do |msg| %>
      		<div class='alert alert-danger'>
			<%= msg %>
	  	</div>
    <% end %>
    	<%= alert %>
	<% else %>
	
	<% end %>





<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render('layouts/messages.html.erb') %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>